server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.250.4.7:8848
  application:
    name: api-passenger
  redis:
    host: 10.250.4.7
    port: 6389
    database: 0
