server:
  port: 8085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.250.4.7:8848
  application:
    name: service-map
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-map?characterEncoding=utf-8&serverTimeZone=GMT%2B8
    username: root
    password: root

logging:
  level:
    com.baomidou.mybatisplus: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#??????????
map:
  key: b808311f7b2ebc7faa4d711e36d8ed76
  sid: 900174
