server:
  port: 8007
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.250.4.7:8848
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-order?characterEncoding=utf-8&serverTimeZone=GMT%2B8
    username: root
    password: root
  redis:
    host: 10.250.4.7
    port: 6389
    database: 0
logging:
  level:
    com.baomidou.mybatisplus: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
#一个服务设置多个端口
spring:
 profiles: 8007
server:
  port: 8007

---
spring:
  profiles: 8008
server:
  port: 8008
