server:
  port: 8082

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.250.4.7:8848
  application:
    name: service-verificationcode

logging:
  level:
    com.baomidou.mybatisplus: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
